# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

POLICY_MANAGER_URL=http://ranger:6080
SYNC_SOURCE=unix
MIN_UNIX_USER_ID_TO_SYNC=500
MIN_UNIX_GROUP_ID_TO_SYNC=500
SYNC_INTERVAL=1

logdir=/var/log/ranger/usersync
piddir=/var/run/ranger

rangerusersync_password=rangerR0cks!

unix_user=ranger
unix_group=ranger

SYNC_LDAP_ENABLE_PAGED_RESULTS=false
